variable "name" {}
variable "name2" {}
variable "namespace" {}
variable "projectName" {}
variable "projectPrefix" {}
variable "url" {}
variable "api_p12_file" {}
variable "region_one" {}
variable "zone_one_a" {}
variable "zone_one_b" {}
variable "zone_one_c" {}
variable "region_two" {}
variable "zone_two_a" {}
variable "zone_two_b" {}
variable "zone_two_c" {}
variable "region_three" {}
variable "zone_three_a" {}
variable "zone_three_b" {}
variable "zone_three_c" {}
variable "gateway_type" {}
variable "xcs_tf_action" {}
variable "tags" {}
variable "sshPublicKey" {}
variable "sshPublicKeyPath" {}
variable "xcs_tenant" {}
variable "instance_type" {}
variable "cidr_one" {}
variable "cidr_two" {}
variable "cidr_three" {}
variable "tenant" {}
# variable "stack_name" {}
variable "agility_namespaces" {}

